const actionTypes = {
  // in
  SEND_MESSAGE: "SEND_MESSAGE",
  SEND_GREETING: "SEND_GREETING",
  // out
  ON_RECEIVED_MESSAGE: "ON_RECEIVED_MESSAGE",
  ON_RECEIVED_GREETING: "ON_RECEIVED_GREETING",
  ON_MEMBER_JOINED: "ON_MEMBER_JOINED"
};

module.exports = actionTypes;
