export const SUBMIT_NEW_MESSAGE = "SUBMIT_NEW_MESSAGE";
export const SEND_GREETING = "SEND_GREETING";
export const REMOVE_MESSAGES = "REMOVE_MESSAGES";
export const ADD_TEST_MESSAGES = "ADD_TEST_MESSAGES";
export const FETCH_MESSAGES = "FETCH_MESSAGES";
//socket
export const SOCKET_ON_RECEIVED_MESSAGE = "SOCKET_ON_RECEIVED_MESSAGE";
export const SOCKET_ON_RECEIVED_GREETING = "SOCKET_ON_RECEIVED_GREETING";
